### PR TITLE
[BREAKING] Single python entry point & hydra based configuration

### PR DESCRIPTION
**Pull request by cloderic**
This is a major refactor of Cogment Verse with 2 objectives:

- Reduce complexity to use and develop new agents
- Improve run configuration

What's has been done:

- Single entry point creating and managing multiple underlying local process
- Refactor the definition of action/observation using "space" definitions and values similarly to Gym
- Only require Node.JS to develop web views, not to use them
- Port and test gym classic control and box2d environments
- Port existing a2c and behavior cloning implementations 

What should be done quickly -> 

- Test Atari environments
- Integrate Minatar environments
- Integrate Port Procgen environments
- Port µ0 actor implementation from the previous cogment-verse

### CODE REVIEW

**Comment by saikrishna-1996** [comment]
Box2D only installs with latest version of swig.
`brew install swig` on Mac

**Comment by saikrishna-1996** [comment]
Could not find `run/simple_dqn` when running lunar lander BC. could you push it?
```
python -m main +experiment=simple_bc/mountain_car services/environment=lunar_lander
In 'config': Could not find 'run/simple_dqn'

Available options in 'run':
        headless_play
        observe
        play
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///Users/AIRSai/cogment-verse/config
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by cloderic** [comment]
@saikrishna-1996 just pushed fixes for those two issues

**Comment by cloderic** [comment]
sb3 support will require this PR to be merged https://github.com/DLR-RM/stable-baselines3/pull/780 as we are using gym >= 0.22 to have good support for headless rendering on Mac and everything is in the same package.

**Comment by cloderic** [comment]
Not everything is fully ported back but it's been in use for >6 months, it's ready to be the new default branch, the old `main` is now available at https://github.com/cogment/cogment-verse/releases/tag/v0.1-prehydra

**Pull request merged**
